# Generated by Django 3.0.3 on 2020-04-03 05:36

from django.db import migrations, models
import station.constants
import station.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccelerometerXyz',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accelerometer_xyz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmbientLightState',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('state', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ambient_light_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmbientLightValues',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ambient_light_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatteryLevel',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'battery_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompassHeading',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('heading', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compass_heading',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompassXyz',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compass_xyz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('online_devices', models.TextField(blank=True, null=True)),
                ('offline_devices', models.TextField(blank=True, null=True)),
                ('is_setup', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'humidity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PressureAltitude',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pressure_altitude',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PressurePressure',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pressure_pressure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PressureTemperature',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pressure_temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RainState',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('state', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rain_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RainValues',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rain_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationLocation',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('is_actual', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationState',
            fields=[
                ('ROWID', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('state', models.IntegerField(blank=True, choices=[(station.constants.StationState['UNKNOWN'], -1), (station.constants.StationState['OFFLINE'], 0), (station.constants.StationState['SETUP_BOOT'], 1), (station.constants.StationState['ONLINE'], 2), (station.constants.StationState['RESTART_REQUESTED'], 3), (station.constants.StationState['RESTARTING'], 4), (station.constants.StationState['SLEEP_REQUESTED'], 5), (station.constants.StationState['SLEEPING'], 6), (station.constants.StationState['WAKE_REQUESTED'], 7), (station.constants.StationState['SETUP_WAKE'], 8), (station.constants.StationState['CALIBRATE_REQUESTED'], 9), (station.constants.StationState['CALIBRATING'], 10), (station.constants.StationState['UNREACHABLE'], 11)], null=True)),
            ],
            options={
                'db_table': 'station_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterTemperature',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WindDirection',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wind_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WindSpeed',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wind_speed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RainGauge',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rain_gauge',
                'managed': True,
            },
        ),
    ]
