# Generated by Django 3.0.3 on 2020-04-01 04:32

from django.db import migrations, models
import station.fields


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryLevel',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'battery_level',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PressureValues',
        ),
    ]
