# Generated by Django 3.0.3 on 2020-04-01 05:29

from django.db import migrations, models
import station.fields


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_auto_20200401_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainGauge',
            fields=[
                ('ROWID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', station.fields.UnixDateTimeField(assume_milliseconds=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rain_gauge',
                'managed': True,
            },
        ),
    ]
