version: '3.7'

services:
  anemio-radio-daemon:
    build:
      ./radio-daemon
    restart: always
    volumes:
      - anemio-data:/data/anemio
    networks:
      - anemio-net
    env_file:
      - .radio-daemon.prod.env
    privileged: true
    devices: 
      - /dev/gpiomem
    environment:
      - UDEV=1
    command: [ "python", "./run.py", "--interactive-testing" ]

  anemio-web-redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    volumes:
      - anemio-redis:/data
    networks:
      - anemio-net

  anemio-web-memcached:
    image: memcached:alpine
    restart: always
    expose:
      - 11211
    entrypoint:
      - memcached
      - -m 64
    networks:
      - anemio-net

  anemio-web-celery:
    build: ./web-server
    command: celery -A anemio worker -l info
    volumes:
      - ./web-server:/home/anemio/app
    depends_on:
      - anemio-web-redis

  anemio-web-celery-beat:
    build: ./web-server
    command: celery -A anemio beat -l info
    volumes:
      - ./web-server:/home/anemio/app
    depends_on:
      - anemio-web-redis

  anemio-web-traefik:
    image: "traefik:v2.0.0-rc3"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=kowaleskij@gmail.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "anemio-certs:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  anemio-web-django:
    depends_on:
      - anemio-web-traefik
      - anemio-web-redis
      - anemio-web-memcached
      - anemio-web-celery
      - anemio-web-celery-beat
    restart: always
    build: ./web-server
    volumes:
      - anemio-data:/data/anemio
    networks:
      - anemio-net
    env_file:
      - .web-server.prod.env

volumes:
  anemio-data:
  anemio-redis-data:
  anemio-certs:

networks:
  anemio-net:
