version: '3.7'

services:
  anemio-daemon:
    build:
      ./radio-daemon
    restart: always
    volumes:
      - anemio-data:/data/anemio
    networks:
      - anemio-net
    env_file:
      - .radio-daemon.prod.env
    privileged: true
    devices: 
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - UDEV=1
    command: [ "python", "./run.py", "--interactive-testing" ]

  anemio-web-redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    volumes:
      anemio-redis:/data
    networks:
      - anemio-net

  anemio-web-memcached:
    image: memcached:alpine
    restart: always
    expose:
      - 11211
    entrypoint:
      - memcached
      - -m 64
    networks:
      - anemio-net

  anemio-web-nginx:
    build:
      - ./web-server/nginx
    restart: always
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./web-server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - anemio-certs:/etc/letsencrypt
    env_file:
      - .web-server.prod.env
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/anemio.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  anemio-web-django:
    depends_on:
      - anemio-web-nginx
      - anemio-web-redis
      - anemio-web-memcached
    restart: always
    build:
      ./web-server
    volumes:
      - anemio-data:/data/anemio
    networks:
      - anemio-net
    env_file:
      - .web-server.prod.env

volumes:
  anemio-data:
  anemio-redis-data:
  anemio-certs:

networks:
  anemio-net:
