"""
Django settings for anemio project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# We will try to load environment vars. This is helpful if we are using a .env file, versus setting all our environment variables.
from dotenv import load_dotenv
from pathlib import Path
env_path = os.getenv('ANEMIO_ENVIRONMENT_FILE_PATH', None)
if env_path is None:
    env_path = Path('.') / '.prod.env'
try:
    load_dotenv(env_path, verbose=True)
except IOError:
    try:
        load_dotenv()
    except IOError:
        pass

# Basic settings
# ------------------------------------
# Full filesystem path to the project.
PROJECT_APP_PATH = os.path.dirname(os.path.abspath(__file__))
PROJECT_APP = os.path.basename(PROJECT_APP_PATH)
PROJECT_ROOT = BASE_DIR = os.path.dirname(PROJECT_APP_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.getenv('DEBUG', 0))

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1').split(',')


# Application definition
# ------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_api_key',
    'django_filters',
    'constance.backends.database',
    'constance',
    'django_celery_results',
    'django_celery_beat',
    'station'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'anemio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Static Files
# ------------------------------------
# URL prefix for static files.
# Example: 'http://media.lawrence.com/static/'
STATIC_URL = '/static/'

# Absolute path to the directory static files should be collected to.
# Don't put anything in this directory yourself; store your static files
# in apps' 'static/' subdirectories and in STATICFILES_DIRS.
# Example: '/home/media/media.lawrence.com/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


# WSGI
# ------------------------------------
WSGI_APPLICATION = 'anemio.wsgi.application'


# Databases
DJANGO_DB_NAME = os.getenv('DJANGO_DB_NAME', None)
DJANGO_DB_NAME = DJANGO_DB_NAME if DJANGO_DB_NAME is not None else os.path.join(BASE_DIR, 'django.db')

ANEMIO_DB_NAME = os.getenv('ANEMIO_DB_NAME', None)
ANEMIO_DB_NAME = ANEMIO_DB_NAME if ANEMIO_DB_NAME is not None else os.path.join(BASE_DIR, '../../radio-daemon/anemio.db')

# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# ------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DJANGO_DB_NAME,
    },
    'station': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ANEMIO_DB_NAME,
    }
}


# Database routers
# https://docs.djangoproject.com/en/3.0/topics/db/multi-db/
# ------------------------------------
DATABASE_ROUTERS = ['anemio.dbrouters.StationRouter', 'anemio.dbrouters.DefaultRouter']


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
# ------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
# ------------------------------------
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Rest framework
# ------------------------------------
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissions'
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1/second',
        'user': '10/sec'
    }
}

# Caches
# ------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': os.getenv('ANEMIO_MEMCACHED_URL', '127.0.0.1:11211'),
    }
}


# Celery (task queue / scheduling)
# ------------------------------------
CELERY_BROKER_URL = os.getenv('ANEMIO_CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'  # Uses django "default" (memcached) cache.
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_RESULT_EXPIRES = CELERY_TASK_RESULT_EXPIRES = 14400  # 4 hours - this value is expressed as the time in seconds that we keep results.


# Constance settings (for global config)
# ------------------------------------
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_DATABASE_CACHE_BACKEND = 'default'
CONSTANCE_CONFIG = {
     'PWS_API_KEY': ('test', 'Personal weather station (PWS.com) API key for posting the station data., '
                     'PWS API Key'),
}
